### ISSUE TITLE
R docker image does not serve /get/web/ path

### ISSUE THREAD

**Issue by almereyda** [stencila/stencila#167]
After running

```
docker run --detach --publish=7373:7373 stencila/ubuntu-14.04-r-3.2 stencila-r demo/stencils/kitchen-sink serve ...
```

I manage to open http://localhost:7373/demo/stencils/kitchen-sink/ in the browser, which renders partly broken.

![bildschirmfoto von 2016-03-26 13-33-51](https://cloud.githubusercontent.com/assets/1645308/14060067/8389c3a2-f357-11e5-91e0-3b32526646ec.png)

**Comment by nokome** [comment]
Hi @almereyda , thanks for submitting this. So, there is a couple of things going on here:

- the kitchensink stencil hasn't been updated for a long time and has elements and directives that are not supported yet by the Substance-based front-end - the "Unsupported" grey bits (sorry, need to update that stencil and the docs!)

- the 404s are actually sort of intentional; so that people can use a component (a sheet or a stencil) when offline, the generated HTML first tries to get the CSS and JS locally from `/get/web` and if that fails falls back to `https://stenci.la/get/web`; what has not been done yet is to bundle the compiled CSS and JS into the R and Python packages - then you wouldn't get those 404s; if there is a more elegant way to do this that doesn't cause 404s I'd love suggestions

You might like to try this instead: `docker run --detach --publish=7373:7373 stencila/ubuntu-14.04-r-3.2 stencila-session` (this is the command run by `worker.py` on the hub). Then you can play with any of the published components on the font page at https://stencila by using their 'address' e.g.

- http://localhost:7373/demo/sheets/simple-r/
- http://localhost:7373/stencila/blog/underneath-sheets

What happens here is that if the component is not found locally (i.e. in `/home/stencila/store` on that Docker container) then it clones the repo for that component (that's why the first time it may take a little while to get a particular component).

**Comment by nokome** [comment]
Handle this more gracefully by (a) copying the compiled `web` module into the Docker images, (b) if the embedded server cannot find `web/...` files then redirecting to `https://stenci.la/get/web/...` (for when using R or Python packages outside of Docker)

**Comment by nokome** [comment]
Closing this as it's outdated (change in underlying architecture)
