### ISSUE TITLE
Trying to build a docker image with stencila results in Unsupported OS.

### ISSUE THREAD

**Issue by scottaubrey** [stencila/stencila#1708]
When trying to create a docker container for a simple express API around the stencila/node I've run into this issues on my AppleSilicon mac running `yarn` in the container:

```
# This file contains the result of Yarn building a package (@stencila/node@npm:2.0.0-alpha.17)
# Script name: install

/opt/epp-encoda/node_modules/@stencila/encoda-2-0-0/install.cjs:40
  throw new Error(
  ^

Error: Unsupported OS: linux, architecture: arm64. To request support, please submit an issue with these details at https://github.com/stencila/stencila/issues.
    at /opt/epp-encoda/node_modules/@stencila/encoda-2-0-0/install.cjs:40:9
    at Object.<anonymous> (/opt/epp-encoda/node_modules/@stencila/encoda-2-0-0/install.cjs:43:3)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:22:47
```

**Comment by nokome** [comment]
This error occurs because at present we don't build Node.js binary addons for Linux/ARM64. Unfortunately, Github Actions (where we do builds) does [not yet support ](https://github.com/actions/runner-images/issues/5631) this architecture. It seems like the best alternative might be to use an externally hosted runner using [BuildJet](https://buildjet.com/for-github-actions/docs/runners/hardware), [Actuated](https://actuated.dev/blog/native-arm64-for-github-actions), or similar.

**Comment by nokome** [comment]
I ended up using BuildJet (which was very straightforward) and Linux/ARM is now part of releases https://github.com/stencila/stencila/releases/tag/v2.0.0-alpha.18. Install tests (although not in a Docker container) is also done on Linux/ARM: https://github.com/stencila/stencila/actions/runs/6621874415/job/17986522390
