### ISSUE TITLE
@stencila/types doesn't appear to exist?

### ISSUE THREAD

**Issue by simonwinter** [stencila/stencila#1814]
When running lint, I get the following error:

```
> @stencila/web@2.0.0-alpha.23 lint
> eslint 'src/**/*.ts' && prettier --check .


/Users/simon/dragonfly/stencila/web/src/clients/nodes.ts
  1:27  error  Unable to resolve path to module '@stencila/types'  import/no-unresolved
```

![CleanShot 2023-12-11 at 20 42 10](https://github.com/stencila/stencila/assets/1104537/089c16be-dad3-4dde-8480-e862ae6cdeea)

It is installed, however it looks to me like the package is pointing to an old directory?

![CleanShot 2023-12-11 at 20 45 23](https://github.com/stencila/stencila/assets/1104537/7c123917-3638-409b-81a7-3ab8bf62c784)

**Comment by nokome** [comment]
Yes, I think this is because `@stencila/types` is a package (in the `ts` folder) in the same NPM workspace as `web` (see the root `package.json`). So `web` looks for it there, in the sibling `ts/dist` folder. However, if you have not yet built the `ts` module then it is not there and so eslint complains.

That is why the `web/Makefile` builds `ts` before doing anything else:

https://github.com/stencila/stencila/blob/f3b42cff91d9abcf4af71831b3833262c8e112e1/web/Makefile#L4-L10

I'll create a PR which adds some docs to explain this for those who aren't using `make`.
