### ISSUE TITLE
chore(web dev): add a Dockerfile to make it easier to build `/web/dist`

### ISSUE THREAD

**Issue by nokome** [stencila/stencila#1819]
### Why?

Developers who are not-working on the `web` module would like to be able to use the latest browser-based UI without having to install node and all dependencies and without waiting for a new release.

### What

- [ ] A `build.Dockerfile` based on `FROM node:20` which runs `npm run build`
- [ ] A `make build-in-docker` recipe which mounts the local `dist` folder and builds into it (make sure use is set correctly!)
- [ ] Some documentation in the web/README.md

**Comment by simonwinter** [comment]
While working on this, I've found some interesting bugs when building the web package. A lot of these kind of statements:


![Image](https://github.com/stencila/stencila/assets/1104537/1688baf5-c8e5-44a0-a348-fdbcc4944f48)


```sh
[Error: ENOENT: no such file or directory, open '/home/node/app/node_modules/@parcel/runtime-js/lib/runtime-659e4fc3808749a6.js'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/node/app/node_modules/@parcel/runtime-js/lib/runtime-659e4fc3808749a6.js'
}

```

According to https://github.com/parcel-bundler/parcel/issues/7853, the issue is possibly related to failing css selectors. I thought this could be related to #1799, however, even removing the typography plugin completely still has issues.

Locally, cleaning `.parcel-cache` fixes some of this, but the build still fails. My guess is that this is related to upgrading packages a month or so back? 

---

In order to get the build working as expected, I found I can change the build command to:

```
parcel build --no-scope-hoist
```

However, this means that the main.js is around 1.2MB! We do have the `gz` & `br` versions - hopefully we can serve those instead.
