### ISSUE TITLE
feat(instruction block node): Custom instruction block node

### ISSUE THREAD

**Issue by simonwinter** [stencila/stencila#1931]
### Summary

Implement custom instruction block node web component

**Comment by nokome** [comment]
I'm going to start on making sure that the `dom.html` for `InstructionBlock` and `InstructionInline` is being rendered properly. This is what it looks like now:

https://github.com/stencila/stencila/blob/953840d2c826aa93357a08df858c20dd41a0a95d/examples/nodes/instruction-block/instruction-block.dom.html

```html
<stencila-article id=art_1111111D root>
  <section slot=content>
    <stencila-instruction-block messages='[{"type":"Message","parts":["4x10 table"]}]' id=isb_11111112>
    </stencila-instruction-block>
    <stencila-instruction-block messages='[{"type":"Message","parts":["top five highest mountains, with height in metres"]}]' id=isb_11111114 assignee=insert-table>
    </stencila-instruction-block>
    <stencila-instruction-block messages='[{"type":"Message","parts":["Improve this paragraph."]}]' content='[{"type":"Paragraph","content":[{"type":"Text","value":"Target paragraph."}]}]' id=isb_11111118>
    </stencila-instruction-block>
    <stencila-instruction-block messages='[{"type":"Message","parts":["please improve this paragraph."]}]' content='[{"type":"Paragraph","content":[{"type":"Text","value":"Another paragraph."}]}]' id=isb_1111111C assignee=anne>
    </stencila-instruction-block>
  </section>
</stencila-article>
```

The messages and message parts need to be expanded into elements (rather than using the default of JSONizing them into attributes). Also need to ensure that any `suggestion` is expanded into an element.

**Comment by nokome** [comment]
@kusalekanayake could you make a start on designs for these nodes.

**Comment by kusalekanayake** [comment]
Initial thoughts had me thinking along the lines of this?

![Image](https://github.com/stencila/stencila/assets/16539995/90f71ce1-d4f0-47c1-8725-56dc278b45a0)

**Comment by nokome** [comment]
Thanks @kusalekanayake. Some initial thoughts:

- I'm not comfortable with the title "AI Assistant". I feel like that is going to get dated very quickly and may become a turn off for some users. We are trying to move away from the idea that we've just bolted on AI integration towards treating AI assistants as collaborators like human collaborators. Indeed the "other party" in one of these conversations could be a "human assistant" who you have delegated a task too. Maybe "Assistant" or "Task" or "Command". I'll go with "Task" below to mean either an `InstructionBlock` or an `InstructionInline`.

- We need to think about how this links to, or is the same as, (from a UX perspective) the "slash command" popup as in Notion that we discussed previously. i.e. how does the user actually create a "Task". I was anticipating that when you type "/ equation for mutual information" at the start of a line in either the visual editor or the Markdown editor that you create a "Task" (an `InstructionBlock` is inserted into the document). As you are typing that in, the semantic matching algo that @brettc is currently working on will come up with a list of candidate assistants to perform the task. In this case, our specialized `insert-math-block` assistant will be at the top of the list and will be the `assignee` of the `InstructionBlock` unless the user chooses another assistant (e.g. because they didn't actually want math but instead wanted a paragraph describing the equation). Here is the start of a real example:

```json
{
  "$schema": "https://stencila.org/Article.schema.json",
  "@context": "https://stencila.org/context.jsonld",
  "type": "Article",
  "content": [
    {
      "type": "InstructionBlock",
      "id": "9f6bcf22-5d7e-4717-b70b-8cff5e05127f",
      "assignee": "insert-math-block",
      "messages": [
        {
          "type": "Message",
          "parts": [
            {
              "type": "Text",
              "value": "equation for mutual information"
            }
          ],
          "authors": [
            {
              "type": "Person",
              ...
            }
          ]
        },
 ```

- Given the above, I think the dropdown for the assistant should go next to the text input at the bottom or better still just become part of the updates-as-you-type-dropdown under the text.

- It is possible to assign a task to one of the "base assistants" (e.g. `openai/gpt-4`, `google/gemini-pro`) as in the design but most of the time users will want to use one of our specialized assistant (which delegate to the specialized assistants) because they have better prompts and enforce the return type of the block or inline content. The specialized assistants delegate to the base assistant depending on what API keys are defined. For example, here is a list of assistants that I get when I run `cargo run -p cli assistants` when I set the `GOOGLE_AI_API_KEY` env var but not for any of the other providers:

![image](https://github.com/stencila/stencila/assets/1152336/11f787be-2ac9-4717-b3c1-e16add260b13)

- I envisage having icons for each specialized assistant that is the same as the icon for the node type (e.g. list) but with sparkles or something for the `stencila/insert-ordered-list` assistant and a wand or something for the (yet to be implemented) `stencila/edit-ordered-list` assistant.

- Both assistants used (the specialized one and the base one) should be shown as an icon for each message. I think we should have separate icons for the different AI providers e.g. OpenAI, Google AI, Anthropic. Here what a message looks like for the math example:

```json
{
          "type": "Message",
          "parts": [
            {
              "type": "Text",
              "value": "$$\nI(X;Y) = H(X) - H(X|Y)\n$$"
            }
          ],
          "content": [
            {
              "type": "MathBlock",
              "code": "I(X;Y) = H(X) - H(X|Y)",
              "mathLanguage": "tex",
              "authors": [
                {
                  "type": "AuthorRole",
                  "author": {
                    "type": "SoftwareApplication",
                    "id": "google/gemini-pro",
                    "name": "Gemini"
                  },
                  "roleName": "Generator"
                },
                {
                  "type": "AuthorRole",
                  "author": {
                    "type": "SoftwareApplication",
                    "id": "stencila/insert-math-block",
                    "name": "Insert Math Block"
                  },
                  "roleName": "Prompter"
                }
              ]
            }
          ],
          "authors": [
            {
              "type": "SoftwareApplication",
              "id": "stencila/insert-math-block",
              "name": "Insert Math Block"
            },
            {
              "type": "SoftwareApplication",
              "id": "google/gemini-pro",
              "name": "Gemini"
            }
          ]
        }
```
(there is some redudancy here due to how we store the messages and the content that we actually insert into the document as the `suggestion` of the `InstructionBlock`)

**Comment by kusalekanayake** [comment]
Thanks for the thoughts @nokome, will go through and apply the feedback today.

**Comment by kusalekanayake** [comment]
Chatted with @brettc about an approach we could take with how we treat the dialog with AI similar to how you mentioned in your previous comment. Will work on some designs this afternoon on how we could go about this. (Started with taking inspiration from Gdocs but somehow extending it to use a wider range of content.)

**Comment by kusalekanayake** [comment]
Instruction block designs.

<img width="1138" alt="image" src="https://github.com/stencila/stencila/assets/16539995/73dec90c-daca-4a02-8a09-2e5f673d6536">

![InstructionBlock - dialog (grey)](https://github.com/stencila/stencila/assets/16539995/9754c81a-b15d-4df7-9c61-2cd76957ce1d)

**Comment by nokome** [comment]
These look good to me @kusalekanayake.

The thing I think need tweaking are the AI suggestions (blue background messages in 2nd image): I feel like they should have a header with the icons (with tooltips) for the assistants involved (as mentioned before there may be more than one) and the "Use" button. Having the icon and button on the left and right of the content makes it a little harder to distinguish what is UI and what is content I am about to inset into my document.

**Comment by kusalekanayake** [comment]
I've moved the non content to the top, added a timestamp for the transaction, and added a name for the agent.
![InstructionBlock - dialog (grey) 3](https://github.com/stencila/stencila/assets/16539995/717483c1-2970-48a5-ada5-aca32bfec321)

**Comment by kusalekanayake** [comment]
And this one has the content highlighted so you are aware of what is being inserted.
![InstructionBlock - dialog (content highlight)](https://github.com/stencila/stencila/assets/16539995/eca87bee-11d6-4af2-8841-7e95c637970a)

**Comment by nokome** [comment]
Thanks for those. I do think the last one is probably best to start some user testing with.
