### ISSUE TITLE
feat(design): chrome

### ISSUE THREAD

**Issue by simonwinter** [stencila/stencila#1962]
### Summary

Update the chrome to reflect the new design (see below):

- [ ] Tool bar:
  - [ ] Views dropdown
  - [ ] Format dropdown
  - [ ] Sync status icon
  - [ ] info button
  - [ ] print button
- [ ] Side bar:
  - [ ] open / close file browser panel
  - [ ] settings
- [ ] File tabs
- [ ] Editor area

![Source view insert menu](https://github.com/stencila/stencila/assets/1104537/533d339d-bbf4-41d4-ac0e-2e35d9ab9138)

**Comment by nokome** [comment]
Thanks for this @simonwinter. A couple of comments:

- The Format selector only applies to the `SourceView` and in #1958 I proposed to move that to the bottom panel of the code editor (Mike has already done that).

- In this mockup authors have multiple roles. But as I said in Discord:

> Does an author have potentially many roles? E.g. Prompter and writer? 

> Yes, but the data model requires that we'd have to to have repeats e.g.

```json
"authors": [
    {
      "type": "AuthorRole",
      "author": {
        "type": "Person",
        "name": "Bob"
      },
      "roleName": "Checker"
    },
    {
      "type": "AuthorRole",
      "author": {
        "type": "Person",
        "name": "Bob"
      },
      "roleName": "Approver"
    }
  ]
```

> I don't think that is an issue and it would be fine in the UI to have multiple entries for the same author - I don't think we should try to jump through hoops to be clever about grouping roles by author or similar

I said that mainly to reduce the work required. But also having multiple entries for a single author is potentially useful because it shows the order that authorship contributions were made.
