### ISSUE TITLE
feat(kernel): avoid rebuilds when changing kernel scripts

### ISSUE THREAD

**Issue by brettc** [stencila/stencila#2121]
### Summary

The kernels are embedded in the stencila binary. Currently, when any iterative changes to these kernels forces a rebuild. It would be nicer to have them embedded only in the release to avoid this (much like the assistants)

**Comment by nokome** [comment]
I noticed the other day that this is occurring. That is because we are using `include_str` rather than the `rust-embed` crate as we do in prompts (fka assistants):

```rust
    fn microkernel_script(&self) -> String {
        include_str!("kernel.py").to_string()
    }
```

But I don't think we should change this since it will only add code/dependencies and only affects developers, who should really only be running `cargo test -p kernel-python` (and so not triggering large rebuilds) when making changes to kernel scripts.
