### ISSUE TITLE
fix(web): show provenance highlighting when node card expanded

### ISSUE THREAD

**Issue by nokome** [stencila/stencila#2327]
Currently provenance highlighting only shows when it is turned on for the whole document. Previously it showed when the node card was expanded for a paragraph. Previously provenance highlighting was also working for code but not does not seem to show at all (even when turned on for whole document).

**Comment by mike-parkin** [comment]
Hey @nokome , I've found the source of this regression.

It relates to the EntityContext that is triggering when the cardOpens 

```
  @provide({ context: entityContext })
  @state()
  protected context: EntityContext = {
    nodeId: this.id,
    cardOpen: false,
  }
```

The authorship is looking for its nearest parent entity ie. the paragraph, for checking if the card is open.

Ever since the `stencila-text` element was declared as a subclass of `Entity` in the ts, it has become the provider for the authorship elements thus broken the flow. If I change the Text to subclass `LitElement` instead of `Entity` that should fix the problem... But i would like to check that this will not have any downstream effects, as I forgot the reason for decalring the Text class in the first place

```
export class Text extends Entity {
  override render() {
    return html`<slot></slot>`
  }
}
```

**Comment by mike-parkin** [comment]
TL:DR; for the above,

Does the `stencila-text` (`nodes/text.ts`) element need to be an `Entity` subclass or can I swap it for a LitElement

**Comment by nokome** [comment]
> Does the `stencila-text` (`nodes/text.ts`) element need to be an `Entity` subclass or can I swap it for a LitElement

No I don't think it needs to be. When you swap it out to be a `LitElement` can you add a comment noting the above so it does not get changed back.

**Comment by nokome** [comment]
Fixed
