### ISSUE TITLE
fix(web): mermaid diagram text labels

### ISSUE THREAD

**Issue by nokome** [stencila/stencila#2344]
The test labels on Mermaid diagrams are broken e.g.:

![image](https://github.com/user-attachments/assets/d7e8e87a-c71d-4d9c-9be1-77f35f804e34)

Note that there are several types of Mermaid diagram (see the `stencila/new/figure-*` prompts or just look at the Mermaid docs for that) and I'm not sure if this is a problem for all. I suspect it is and that it has something to do with the default theme. I suggest testing it out with the default theme disabled (by removing it in dev tools?) and using `serve` to view on localhost first.

**Comment by mike-parkin** [comment]
I think your hunch is correct, this is what happens when I toggle of the default.css file in the dev tools.

![image](https://github.com/user-attachments/assets/ed361c8b-0fce-4dc6-86c0-9cd6e14f1ac0)

this rule from the tw base seems to be the culprit, which is probably why its going past the shadow doms:

![image](https://github.com/user-attachments/assets/970c4b94-00dd-435d-ac9f-47405f3e204a)

will see where i can override it

**Comment by nokome** [comment]
> will see where i can override it

Maybe do it close the the Mermaid rendered SVG element (I can't remember where that is). I say that because when we allow authors to add their own themes we don't want the same thing to happen. There might be other style rules that we ensure that SVG element is insulated from:

![image](https://github.com/user-attachments/assets/f8f18130-d104-481d-9a61-51feb1d4ff4b)

**Comment by nokome** [comment]
Fixed by 7521652bb47a137adeca25bfe035515f0396e6cc
