### ISSUE TITLE
bug(vscode) - command enter...`Not executed`

### ISSUE THREAD

**Issue by jduckles** [stencila/stencila#2380]
Working on main -> b7c16fb29e

It appears since the `s/::: new/::: create/` update that I need to finish code fences with `>>`. 

On a Mac when I command-Enter at the end of one of these lines I get: 

<img width="1017" alt="image" src="https://github.com/user-attachments/assets/0c716c82-5436-45fa-bf59-b3dc170f0730">

Then I can click Run and it works. 

If I cursor back to the front of the line before the `:::` the command enter works, but it does not work at the end of the line, either before or after the `>>`

**Comment by nokome** [comment]
Yes, I have noticed this (and also found it annoying). What happens is that we keep a mapping of character position in the document to the node and node property in the document tree (like this [test snapshot](https://github.com/stencila/stencila/blob/main/examples/nodes/instruction-block/instruction-block.smd.encode.map)). For some reason, the mapping is incorrect at the end of the command line so that when you `Ctrl+Enter` there is no executable node found at that position. I've checked the obvious place where the mapping is generated but couldn't fine the problem. I'll have to do some tests.

**Comment by nokome** [comment]
The mapping can be out of date (by up to 500ms) if `Ctrl+Enter` is pressed before the latest debounced changes have been parsed. Also there is a out-by one issue with mapping at the end of the file.

So I've fixed this by adding and using this function which feels like a more robust solution, which reflects the user's intent) than trying to fix mapping race condition now (although it does need to be fixed for other reasons anyway).  

```rust
    /// Get the [`NodeId`] closest to the position (if any)
    ///
    /// Searches towards the start of the line, and then the start of the previous
    /// line for a node and returns its id.
    pub fn node_id_closest(&self, mut position: Position) -> Option<NodeId> {
```
