### ISSUE TITLE
fix(describe) - Describe is destructive of the block its describing

### ISSUE THREAD

**Issue by jduckles** [stencila/stencila#2409]
If I wrap a code block in `::: describe <codeblock> :::`, I get a decent description of that code block, but it removes the code block itself. Could we create a way to let Stencila describe something easily, but not remove it when describing it. For most cases, like turning a code block into step-by-step prose, I think the user would most likely want to keep the original content. 

If this is intentional feel free to close.

**Comment by kusalekanayake** [comment]
![CleanShot 2024-11-14 at 10 12 35](https://github.com/user-attachments/assets/a19c440a-98f1-47d0-8655-cd3057a7b5ba)

**Comment by kusalekanayake** [comment]
Using colons instead was ok though. 
![CleanShot 2024-11-14 at 10 18 51](https://github.com/user-attachments/assets/e2b15e62-c841-474e-ac8f-e5f10cf8003d)

**Comment by jduckles** [comment]
hmmmm, okay, see #2418 for more `::: describe` fun.

**Comment by nokome** [comment]
This is intentional behaviour, consistent with the other commands: the content contained by a command is either new content (`create`) or is intended to be changed (`edit` and `fix`). See https://github.com/stencila/stencila/issues/2418#issuecomment-2481549021 for how to specify what you want to describe.

**Comment by jduckles** [comment]
Closing as this is expected behavior.
