### ISSUE TITLE
feature(vscode) - Automatically open Preview?

### ISSUE THREAD

**Issue by jduckles** [stencila/stencila#2423]
@kusalekanayake and I were talking today about the user experience for Walkthroughs and how they don't necessarily have the same experience when the user is just reading the Markdown as they would have reading the rendered preview (clickable links, richer styling etc). 

Would it make sense for opening a document in the Stencila VSCode extension to automatically open the preview? Or do we want to keep that as a user-choice?

I'm sure you've thought about this @nokome, just wanted to invite others to weigh in too on how they feel it should / could be.

**Comment by kusalekanayake** [comment]
This came up as a part of discussion around potentially having a gif/demo of opening the preview on the readme.

**Comment by nokome** [comment]
> opening a document in the Stencila VSCode extension to automatically open the preview

As a user, I would prefer to decide when I open the preview for my own document i.e. I want to opt-in to having half my screen real estate taken up by the preview, rather than that happening automatically all the time (this could be another config option).

Having said that, I think open-preview-by-default makes sense for the walkthroughs.
