### ISSUE TITLE
Wrong download link on Stencila start page

### ISSUE THREAD

**Issue by michael** [stencila/stencila#277]
Currently links to:

https://github.com/stencila/stencila/releases

but should link to:

https://github.com/stencila/desktop/releases

**Comment by nokome** [comment]
This was intentional - with the idea that https://github.com/stencila/stencila/releases would have download links to all the downloads for that release - desktop, node package, R package etc

But for now, your suggestion is better and I've made the change. Soon we should have a custom download page - with autodetection of OS and instructions for downloading packages vian npm etc.

This should really be filed at stencila/hub - but thanks! :smile:
