### ISSUE TITLE
Getting first version of functions to work

### ISSUE THREAD

**Issue by michael** [stencila/stencila#356]
Oliver and I discussed today how to best approach integrating functions with the execution engine. What we need next is an instance of a FunctionManager that allows looking up all available functions during runtime. 

See this API sketch here (WIP): https://github.com/stencila/stencila/pull/355/files

I think we should switch to use the XML definitions only for seeding, not keeping XMLDocument instances in memory as that could get pretty heavy. 

- For a start I suggest postpone function overloading capabilities, just to be quicker with having a first shot of the API and see how it feels. 
- We could start with a number of JS functions (`sum`, `plot`, ...)
- Let's store only the function body as the implementation, since the signature we can derive from the metadata. E.g. we don't need to use eval and can use the Function constructor instead (`new Function ([arg1[, arg2[, ...argN]],] functionBody)`)
- In Stencila 0.27 we compile functions in the context on startup and use the context to run the function later. I wonder if it wouldn't be a better strategy to do function compilation on demand as most of the time only a tiny fraction of the functions is actually used. Once we enable user functions, function implementations could change during runtime, so it may be a good strategy to always ad-hoc compile and run them first. We can introduce caching later (e.g. compute a hash of the function body and recompile if it changed)

@nokome while we are working on putting the pieces together, maybe you could go ahead and work on implementing the most important core functions?

Now I'm just not sure how to best specify them in separate js files without the signature around it. I guess you could have a file sum.js with the following content:

```
return value1 + value2
```

Then in a test execute `new Function(..., functionBody)`.

**Comment by oliver----** [comment]
I don't think it is a good idea to use the function body as persisted source.
Only for a Function Editor embedded in Stencila this makes sense.

Given an interpreter and a piece of source, a more flexible approach would be that the source must be an expression that evaluates to a function instance. 
This would allow to use other/real programming environments to build such 'bundles', with tools that are common in that environment.

**Comment by oliver----** [comment]
@michael @nokome before implementing a bunch of core functions I'd prefer to settle the concepts.

**Comment by oliver----** [comment]
A complex example could look like this:

```
import d3 from 'd3'

export default function a() {
  console.log('first a, then')
  _b()
}

function _b() {
  // use d3
  console.log(d3)
}
```

bundled to:
```
(function(global) {

let d3 = global.d3

return function a() {
  console.log('first a, then')
  _b()
}

function _b() {
  // use d3
  console.log(d3)
}

})(typeof window === 'undefined' ? global : window)
```

**Comment by nokome** [comment]
> I don't think it is a good idea to use the function body as persisted source. Only for a Function Editor embedded in Stencila this makes sense.
>
> Given an interpreter and a piece of source, a more flexible approach would be that the source is an expression that evaluates to a function instance.

I agree, and that is the current approach. At the very least it allows for standalone syntactically valid source files e.g. https://github.com/stencila/stencila/blob/function-updates/tests/function/fixtures/code_include_1_integer.js which can be "included" into the XML. But @oliver----'s  example re helper functions is more compelling. On that note, it will be important for the functions in the standard library to call each other.

The FunctionEditor will know the language of the function (JS, R, Python...) anyway and can have some logic to wrap it appropriately if need be.

The current use of `eval` was just a shortcut and `new Function` could be used to return a function object instead, although I suspect for JS at least we'll need something like what oli suggests.

**Comment by oliver----** [comment]
> On that note, it will be important for the functions in the standard library to call each other.

Good point.

**Comment by michael** [comment]
Yeah the concepts are really not clear yet to... just wrote about testing and debugging - like the development process of Stencila functions. Would be nice to have a smaller scope for testing them, with debugging capabilities on.. however that could be difficult to acchieve accross different languages.

Also should it be possible to call foo() implemented in Python from bar() implemented in Javascript? Then we would need to the complete stack running with context dispatching in order to develop/test.

**Comment by michael** [comment]
see https://github.com/stencila/stencila/issues/357

**Comment by nokome** [comment]
> For a start I suggest postpone function overloading capabilities, just to be quicker with having a first shot of the API and see how it feels.

I think it is important to to have **type** overloading (aka multiple dipatch) from the start. For a purely functional language, with no classes with methods it is especially important. This snippet from Wikipedia explains it well:

>  Function names are usually selected so as to be descriptive of the function's purpose. 
  It is sometimes desirable to give several functions the same name, often because they 
  perform conceptually similar tasks, but operate on different types of input data. 
  In such cases, the name reference at the function call site is not sufficient for identifying 
  the block of code to be executed. Instead, the number and type of the arguments to the 
  function call are also used to select among several function implementations."

A simple example is the sum function. To sum a one-dimensional array of cells in a sheet I'd write `sum(A1:A10)` which get's invisibly, dynamically dispatched to the `sum_array` implementation. To sum a two-dimensional array of cells I'd write `sum(A1:D5)` which get's invisibly, dynamically dispatched to the `sum_matrix` implementation. I don't want to have to write `sum_array(A1:A10)` or `sum_matrix(A1:D5)`.

Previously we did this type of dispatching in Mini at the implementation level. But the current approach is much more well defined, fit's with our typing of Sheets and better allows for future optimizations.

At this stage we don't need to worry about alternative implementations in different languages. We are going to focus on JS. *But*, it is important that we keep this in mind because it is a very powerful aspect. The current implementation of `FunctionDocument` interacts with the abstract `Context` API methods like `defineFunction` and `callFunction` ans should work with `JsContext` and remote contexts over HTTP like `RContext` etc. 

I'm not in favour of trying to optimise too much now. The current `FunctionDocument` works and is tested for JsContext, including type overloading. It just needs to a `FunctionManager` which looks up the function by name `let func = functionManager.getFunction('sum')`, tells it to define itself within the context `func.define('js', jsContext)` (either at startup or JIT) and call itself with a set of arguments `func.call('js', jsContext, {type: 'array[number]', data:...})`. We'll hardcode the use of `jsContext` for now, but this approach is furture proofed towards functions with implementations in varying languages.

**Comment by oliver----** [comment]
I agree that we consider multiple-dispatch at least on the conceptual level from the start.
In general we might want to restrict multifuncs to have at least semantically consistent signatures. Otherwise it will be hard to have a common description and command test cases.

**Comment by nokome** [comment]
> In general we might want to restrict multifuncs to have at least semantically consistent signatures. 

Currently, each multifunc (an `implem`) is checked for consistency in the number and type of overloaded parameter types:

https://github.com/stencila/stencila/blob/function-updates/src/function/FunctionDocument.js#L95

**Comment by oliver----** [comment]
> I think we should switch to use the XML definitions only for seeding, not keeping XMLDocument instances in memory as that could get pretty heavy.

ATM I am not sure. Maybe we can put the Function documents into the center of the Functions picture. Then the XML would be the general abstraction to expose functions -- e.g. consider a hosted service providing functions, which would then expose XML documents (with bundled impementations included). @nokome were you thinking into that direction?

**Comment by nokome** [comment]
> Maybe we can put the Function documents into the center of the picture. Then the XML would be the general abstraction to expose functions... @nokome were you thinking into that direction?

Yes. We can optimise in the future if we need to but this is the most "canonical" way as a first step

> Edit: for our lib repo, this would mean that we create XML files via a bundling step, and use these to seed the FunctionManager.

Yes. That is what [stencila/lib/make.js](https://github.com/stencila/lib/blob/master/make.js) does. I've tried to keep that very simple and lightweight but obviously we may need to make it more sophisticated to deal with things like [your transpilation example](https://github.com/stencila/stencila/issues/356#issuecomment-332630028).

There are also preliminary corresponding implementations `make.py` etc for other languages - as proof of concept for how we can efficiently seed `RContext` and `PythonContext` etc with standard library functions. And have developers using those languages contribute to the lib.

**Comment by oliver----** [comment]
> We can optimise in the future if we need to but this is the most "canonical" way as a first step

Maybe this is a good choice in general, because it is clear interface for others independent of our implementation re bundling tools.
