### ISSUE TITLE
Function Libraries as generic concept

### ISSUE THREAD

**Issue by michael** [stencila/stencila#358]
Here's a proposal after thinking more about how we could streamline the provision of function libraries in a generic way (no matter if they came from a project-specific user function, or are implemented in a github repo).

We propose the following interface to import a library with resolving all the dependencies that are necessary.

```js
functionManager.importLibrary(libraryXML, impls)
```

`libraryXML` is all the meta info we need in Stencila. Looks like this:

```xml
  <library>
    <function>
      <name>sum</name>
      <params>
        <param name="val1" type="any"/>
        <param name="val2" type="any" repeatable="true"/>
      </params>
      <!-- no impls here -->
    </function>
    <function>
      ...
    </funtion>
  </library>
```

impls is a hash of a transpiled source for each language.

```js
let impls = {
  'javascript': '{sum: function(a,b) { return window.stdlib.sum(a,b) }}',
  'python': 'PY_CODE'
}
```

Considerations:

- Stencila function libraries can be used stand-alone outside of Stencila (like without all the meta information needed) ->`import {sum} from 'mini-core'`
- Multi-Dispatch is implemented in a library, not in the Stencila engine. 
  - The concept multi-dispatch should not be exposed to the user, as it is too complicated (no multi-dispatch in visual function editor)
  - Multi-dispatch should be solved on the implementation level: just one module per function. 
- this approach sticks closer to real world development practices (modules, versioning, git workflows,..), that's also how we want to develop our core lib. we let the professional users use their fav. tools
- User functions (aka user-library) should be more lightweight (in memory XML storage), just modularize code in a project and call it from Mini, no need for testing, CI for now. Maybe in the future we want to go more towards an IDE, but that needs more discussion first

@nokome we can further discuss this but we'd also like to pull the things together and the proposed way seems clean to us and fits the requirements we have. I think it's a good comprise between technical capabilities and complexity exposed to users. Now we won't scare coders and won't overwhelm clickers.

**Comment by nokome** [comment]
This is great! Agree with it all and it mirrors my thoughts over the past couple of days as I have been implementing `mini-core`.

Just a couple of peripheral points:

> `<param name="val2" type="any" repeatable="true"/>`

I think we should avoid variadic arguments at this stage. It adds another concept that complicates things for the user and for the function implementer. Instead of having 

    sum(A1:A10, B1:D1)

I suggest

    sum(join(A1:A10, B1:D1))

or

    join(A1:A10, B1:D1) | sum()

This is longer to write but feels more consistent with a purely functional, strongly typed approach. We can implement Excel compatability functions to be variadic `function SUM(...args) { return sum(JOIN(...args)) }` so that if user want to they can still write:

    SUM(A1:A10, B1:D1)

But I think it's best to keep Mini function non-variadic at first - we can add that if people really want it.

> Maybe in the future we want to go more towards an IDE

Maybe, but I doubt it. We really need to avoid scope creep into that area, there are so many good IDE tools already. The main reason for the `<tests>` element is not for development but for having a means of testing that alternative language implementations of the same functions return the same result. This will be essential in the future when we have more advanced dispatching. But it is not something we need to worry about for now.
