### ISSUE TITLE
Tidy-up IssueManager

### ISSUE THREAD

**Issue by oliver----** [stencila/stencila#445]
> WIP: Still refining concepts and technical specification

Concepts:
- Syntax and Runtime Errors: generated by Engine throughout processing of cell expressions
- Checkers and Tests: live independently in the document, attached to the sheet or a range, running after a cell has been evaluated, generating an issue accordingly
- Conditional Formatters: similar to a Checker 
- Comments: live independently in the document, attached to a range or cell

**Comment by oliver----** [comment]
> we do not need a Random Access API for Sheets for this issue

**Comment by Integral** [comment]
Just a few comments:
1) cell state also is a source of issues currently, for instance when you have runtime error or make an assertion it is also an issue
2) there are more complicated scenarios, e.g. for test cells you don't need to aggregate number of passed tests (which are also issues and we are printing them inside issue panel or sidebar) in column or row, but you need to do that for failed tests

**Comment by oliver----** [comment]
> cell state also is a source of issues currently, for instance when you have runtime error or make an assertion it is also an issue

Right. We should use only one way. Cell states are indeed useful for this. Thus I suggest always putting issues in node states (cell, row, col).

**Comment by nokome** [comment]
Just to add some considerations based on feedback and ideas from the recent design workshops:

1. The issues panel is a central and important concept - so good to get it's API right and make it easy for other to contribute checks. For examples of checks that may be added in the future see the "Best practices check" section of https://f1000research.com/articles/3-6/v2

2. The issue markers on the column and row headers are a little confusing. They are intended to indicate there is an issue somewhere on the row/column but suggest that there is a problem with the entire column/row. Maybe drop these and instead provide:
    - auto-scrolling to the relevant cell when the issue is clicked
    - ability to filter issues by column/row/type (including counts)

3. Given that ad-hoc formatting will not be allowed, people want the ability to mark cells as "suspicious", "needs attention", or add some other annotation (the sort of thing that they usually use ad-hoc fromatting for). This could be a part of the issue panel: a user could create a custom issue e.g. "Machine not calibrated", "Needs checking" etc and then use an "apply issue" tool to click on cells and apply the issue to them.

4. This is a somewhat different topic, but related to how test fails are recorded in the issue panel. Instead of having separate test cells it would probably be better to have tests as cell attributes. For example, currently,  if I had 10 cols x 1000 rows of cells that I wanted to apply the same test to, I would have to create 10 cols x 1000 rows of test cells. Instead, if tests were an attribute of cells, then I could create a test and apply it to all those cells. This is also related to having tests defined to each type e.g. a "human height" type might have tests to check value greater than 0 and less then 3m (ie. types have tests and cells can have additional custom tests).

**Comment by Integral** [comment]
@nokome thanks for input
I think we need to rethink the whole thing once again based on new requirements, hope we will come up with generic api

couple of thoughts:
we should rethink what to do with severity, currently test results (passed, failed) are also severity level thing which is maybe wrong idea
what would be severity of custom issue type? like what is severity of "suspicious" cell? should we introduce custom severities or should we force users to bind every custom issue type to one of severity levels?
given 3 and 4, if we are about to introduce custom issues type and thinking about cells (or maybe better range) test state, then we should gave the possibility to use custom issues as test results, for instance if the assertion failed i want to mark range of cells as "suspicious" and see red corner above that range (not on each cell), this make sense, right?

**Comment by Integral** [comment]
you know what i mean? just imagine that this is results of some test assertion and this is "suspicious" data: ![screen shot 2017-11-21 at 14 43 06](https://user-images.githubusercontent.com/182010/33070842-6baf74ac-ceca-11e7-9c8d-33abc921a579.png)

**Comment by nokome** [comment]
@Integral, thanks. Some thoughts:

- I think it's ok to allow users to choose a severity level for a custom issue, the default could be "info"
- I get your idea about marking ranges of cells as failing a particular check but it seems to add a layer of complexity - seems more natural to select a range of cells, apply an issue or test to them and see a red triangle in the ones that fail

Just my $0.02 worth.

**Comment by oliver----** [comment]
I think we need some more discussion.

By now we had the following types of 'issues'
1. syntax- and runtime-errors: are coming from parsing or execution of a cell, bound to a cell
2. type check: is a function run on every cell, whenever it has been evaluated; issue is bound to cell
3. test cell (as it is ATM): a special cell result, that is mapped to an issue (error if failed, and info if succeeded)

There are new requirements:

> Given that ad-hoc formatting will not be allowed, people want the ability to mark cells as "suspicious", "needs attention", or add some other annotation (the sort of thing that they usually use ad-hoc fromatting for). This could be a part of the issue panel: a user could create a custom issue e.g. "Machine not calibrated", "Needs checking" etc and then use an "apply issue" tool to click on cells and apply the issue to them.
These are substantially different, as they are persisted in the model, and not generated via execution. This seems more like a comment type of thing

> This is a somewhat different topic, but related to how test fails are recorded in the issue panel. Instead of having separate test cells it would probably be better to have tests as cell attributes. For example, currently, if I had 10 cols x 1000 rows of cells that I wanted to apply the same test to, I would have to create 10 cols x 1000 rows of test cells. Instead, if tests were an attribute of cells, then I could create a test and apply it to all those cells. This is also related to having tests defined to each type e.g. a "human height" type might have tests to check value greater than 0 and less then 3m (ie. types have tests and cells can have additional custom tests).

That would mean, tests are more like checkers, run on a range of cells, adding a issue according to the result.

Let's discuss the following concepts:
1. Syntax-/Runtime-errors during the evaluation process
2. Checkers/Tests that run whenever a cell has been evaluated
3. Tags created to highlight a cell (can be created on a range for convenience)
4. Comments/markers (with ability to link to a cell/range)

1. and 2. are creating 'issues' dynamically at different stages of a cell's life-cycle
3. and 4. are different concepts that may be used to communicate 'custom issues'

@nokome @michael @Integral do you agree with this summary?

**Comment by oliver----** [comment]
`2.` could be used for dynamic formatting

**Comment by nokome** [comment]
@oliver---- : yes, agree with the categorisation but I'm not sure what the distinction between `3.` and `4.` is - they seem to be the same, why treat them as different?

**Comment by oliver----** [comment]
@nokome thought about something more like cell 'classes' without extra data. These would be stored on the cell instead of an extra entity in the model. But actually we were not having this in the requirements yet. Probably more important is commenting and dynamic formatting.

**Comment by nokome** [comment]
OK. Seems to me that dynamic formatting (aka conditional formatting) is a
separate topic (albeit one that is implemented similarly by adding a
"formatting class" to cell attributes)

On Dec 6, 2017 20:07, "Oliver Buchtala" <notifications@github.com> wrote:

@nokome <https://github.com/nokome> thought about something more like cell
'classes' without extra data. These would be stored on the cell instead of
an extra entity in the model. But actually we were not having this in the
requirements yet. Probably more important is commenting and dynamic
formatting.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/stencila/stencila/issues/445#issuecomment-349554253>,
or mute the thread

**Comment by oliver----** [comment]
Yep. So `2.` is conditional formatting (with complex data, not just rendering classes), Checkers and tests fall into this category. Even `1.` could be seen as something like that.
`4.` is more commenting/discussion. And `3.` if  we really want it, is custom cell categories.

**Comment by Integral** [comment]
I think that if you can present more examples of 3 and 4 that would clarify those concepts. It's hard to understand it good enough now...

**Comment by oliver----** [comment]
For `3.` we do not have set a requirement yet. From an architecture point-of-view this could be an option. Don't know if we really need it.

`4.` comes from @nokome's requirement:

> Given that ad-hoc formatting will not be allowed, people want the ability to mark cells as "suspicious", "needs attention", or add some other annotation (the sort of thing that they usually use ad-hoc fromatting for). This could be a part of the issue panel: a user could create a custom issue e.g. "Machine not calibrated", "Needs checking" etc and then use an "apply issue" tool to click on cells and apply the issue to them.
