### ISSUE TITLE
Improve sizing and position of plots

### ISSUE THREAD

**Issue by nokome** [stencila/stencila#483]
Currently, when you create a plot, it fills the cell but the column width does expand and the result is an unreadble plot. When the user adjusts the column width the plot does not get re-rendered (unless the cell is scrolled out and the in of viewport). 

![peek 2017-12-20 19-55](https://user-images.githubusercontent.com/1152336/34195130-e7da3d70-e5c0-11e7-9d22-df21a77867d1.gif)

Personally, I'd prefer plots to default to floating and be resizable and moveable (offset to defining cell). Although there are some use cases, creating a "grid" of similar plots where it can be useful to have them fixed within the cell.

**Comment by oliver----** [comment]
@Integral what is the state of this?

**Comment by Integral** [comment]
@oliver---- when we were together we decided to do popup like window of predefined size, e.g.:
![screen shot 2018-02-07 at 17 14 15](https://user-images.githubusercontent.com/182010/35920996-82d38d06-0c2a-11e8-9a53-87e4c91aa2e2.png)
We didn't discuss next steps here since then, it was uncertain. Let's discuss/decide and I will continue.

**Comment by oliver----** [comment]
Ok. Thanks.

**Comment by michael** [comment]
We'll do a dedicated Sheets iteration starting next week. We need to solve a bunch of fundamental UX problems related to displaying overflowing charts/tables etc.
