### ISSUE TITLE
More flexible definition of function parameters

### ISSUE THREAD

**Issue by michael** [stencila/stencila#493]
I think we really need variadic args soon.

**Comment by nokome** [comment]
I agree that variadic (repeatable) parameters are required. But I've changed the title because I think it's part of a broader topic of allowing more flexibility in definition the number and type of function parameters that would be better to address in one PR. This deficiency has arisen recently when from implementing several functions.

We use function overloading to keep the number of functions small and the usage more forgiving. For example the `plot`  function can currently take be called as `plot(array[numbers])`, `plot(array[numbers], array[numbers])` or `plot(table)`. See the usage examples at https://github.com/stencila/libcore/blob/master/defs/plot.fun.xml. With the current FunctionSchema these alternatives have to be defined as:

```
    <params>
        <param name="arg1" type="any">
            <description>Either an array or a table</description>
        </param>
        <param name="arg2" type="any">
            <default type="null">null</default>
            <description>An array</description>
        </param>
    </params>
```

This is confusing in function help because actually you can't call `plot` with two `any` arguments and you will get an error (generated by the JS implementation) if you do. 

One option, would be to make the function more restrictive e.g. only `plot(table)` - which would force the user to create a table whenever they wanted to plot something. The other alternative is to all function definitions to have multiple `<usage>` elements e.g. for `plot` (I've added a variadic option as an example, although I don't necessarily propose adding it)

```
<usages>
    <usage>
        <arg name="y" type="number" repeatable="true>
            <description>A sequence of numbers to plot on the y-axis</description>
        </arg>
    </usage>
    <usage>
        <arg name="y" type="array[number]">
            <description>An array of numbers to plot on the y-axis (the x-axis will be the index of the value from 1 to the number of values in the array)</description>
        </arg>
    </usage>
    <usage>
        <arg name="x" type="array[number]">
            <description>An array of numbers to plot on the x-axis</description>
        </arg>
        <arg name="y" type="array[number]">
            <description>An array of numbers to plot on the y-axis</description>
        </arg>
    </usage>
    <usage>
        <arg name="data" type="table">
            <description>A table of data to plot. If</description>
        </arg>
        <arg name="encoding" type="object">
            <description>An object defining the encoding between mark properties e.g. x, y, color,
 size and data</description>
        </arg>
    </usage>
</usages>
```

Although this places more burden on the function author it would provide much clearer guidance for the user.
