### ISSUE TITLE
Feature: break a code cell / append paragraph if entering multiple empty lines

### ISSUE THREAD

**Issue by Integral** [stencila/stencila#518]
I can't edit manuscript of this document, except one cell:
<img width="829" alt="screen shot 2018-02-07 at 01 15 46" src="https://user-images.githubusercontent.com/182010/35887183-889aca00-0ba4-11e8-9e8e-edbc454cac51.png">

E.g. if there is only cells inside body, you can't do anything. You can't remove cell and you can't add any other content.

**Comment by michael** [comment]
Try ESC (focus the isolated node) and ten ENTER (insert new paragraph). But I agree this is not very obvious. Not sure how to solve it yet without introducing extra UI elements.

**Comment by oliver----** [comment]
@Integral our isolated nodes are similar to how Pages treats e.g. tables on OSX. There is a similar problem.
We tried to 'open' cells so that you can at least navigate them with the cursor, but then there is no 'easy' way to select them, except of ESC.
But I agree also, that we should discuss if we find a more intuitive solution to this.

**Comment by Integral** [comment]
Thanks! Without your comments I wasn't able to do that.
Well, this case isn't very simple to find, but a bit ridiculous.
Maybe the good strategy would be that if the person enters few empty lines in code - he will leave the cell? Or maybe the new line after empty first line?

**Comment by oliver----** [comment]
Changed the title, and made it a feature request.

**Comment by oliver----** [comment]
@nokome what do you think about this?
