### ISSUE TITLE
Removing cell using backspace

### ISSUE THREAD

**Issue by Integral** [stencila/stencila#521]
It's seems to be quiet natural to remove empty cell hitting backspace when it's already empty. But currently you can't remove cell being inside it.

**Comment by michael** [comment]
That's because of the nature of an isolated node. You'd need to hit ESC, or toggle the ellipsis menu and then hit backspace.

@nokome do you think we should react on backspace in an empty cell to delete it?

**Comment by nokome** [comment]
> @nokome <https://github.com/nokome> do you think we should react on
backspace in an empty cell to delete it?

Yes, please.

On Feb 7, 2018 12:38, "Michael Aufreiter" <notifications@github.com> wrote:

That's because of the nature of an isolated node. You'd need to hit ESC, or
toggle the ellipsis menu and then hit backspace.

@nokome <https://github.com/nokome> do you think we should react on
backspace in an empty cell to delete it?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/stencila/stencila/issues/521#issuecomment-363603826>,
or mute the thread
