### ISSUE TITLE
Non bold heading

### ISSUE THREAD

**Issue by Integral** [stencila/stencila#528]
If you do cmd-b command on heading+paragraph selection heading will lose it's natural font weight:
![](http://g.recordit.co/i9WfBzre2l.gif)

**Comment by Integral** [comment]
I guess it's not a stencila bug...

**Comment by oliver----** [comment]
This is kind of a css problem.

**Comment by Integral** [comment]
I wouldn't say that it is a css problem, look on markup:
```
<h1 data-id="heading-2" class="sc-heading">
<span data-path="heading-2.content" class="sc-text-property" style="white-space:pre-wrap">Heading <span style="font-weight: normal;">test<br></span>
</span>
</h1>
```
So it's force `font-weight: normal`, we could solve it via css, but it will be a hack.

**Comment by oliver----** [comment]
Ah. interesting.
You are right this is not related to CSS.
It is the native CMD-b handling, because the bold command is disabled for that selection, and obviously we have a regression in the keyboard handling.
We should make sure that we add an extra global event handler for all the native key combos, to prevent the native behavior.

**Comment by oliver----** [comment]
BTW, for other selections (within the heading) it is working as expected.

**Comment by michael** [comment]
Fixed via https://github.com/substance/substance/pull/1156
