### ISSUE TITLE
RFC: Stencila Collaboration via Git

### ISSUE THREAD

**Issue by michael** [stencila/stencila#556]
Just had an idea of a collaboration flow we could implement with a minimum of infrastructure to be provided by Stencila.

## Open Collaboration Workflow

**Me:**

1. Open Stencila Desktop and create a new project
2. File -> Save project on disk (e.g. `~/my-dars/our-paper`)
3. Share project via Github

     ```
     $ cd ~/my-dars/our-paper
     $ git init
     $ git remote add origin https://github.com/michael/our-paper.git
     $ git push origin master
     ```
4. Share Github Repo

**Them:**

5. Clone the Repo, make changes in the editor and push them

     ```
     $ git clone https://github.com/michael/our-paper.git && cd our-paper
     $ stencila . # brings up Stencila Desktop for editing
     $ git add *
     $ git commit -m "reworked introduction chapter"
     $ git push origin master
     ```

**Me:**

6. Accepting the fixes

     ```
     $ git pull
     $ stencila open .
     ```

7. Publish on Stencila Hub or a Publisher
   - Go to https://stenci.la and enter Github url: https://github.com/michael/our-paper.git
   - Or go to elifesciences.org and provide the same url

8. Paper is now available in a reproducible version at: https://stenci.la/michael/our-paper and after peer review at https://elifesciences.org/articles/article-id
    
## Considerations

- Stencila works with bare-metal tool (no platform lock in)
- Use the workflows and tools you prefer (Gitlab, Github)
- Use existing reliable infrastructure
- Keep Stencila Hub slim and maintainable (we use it as a public repository for hosting publications, so people can run them, play with them in the browser and download or clone them to run and edit them locally)

**Comment by apawlik** [comment]
Looks like a very good workflow. If possible, it would be great to have GUI for doing the commits in Stencila (like it is now available in RStudio).

**Comment by michael** [comment]
Yeah we can definitely consider tightly integrating with Git. We just need to have a sound plan of the complete workflow before we do so.

One way to approach it could be that we let the user do a git init in the folder, and once that is done the Desktop app could recognise that and show a prompt for a commit message when you hit save.

Btw you can try out this workflow by following the steps here: https://github.com/michael/documents

**Comment by apawlik** [comment]
Thanks @michael 
I wonder if it would be possible to allow for `git init` from the Desktop app too? It would be available only in a project would be open (i.e not a single file). I think this is how it can be done from RStudio GUI - you can do quite a few things via the menu, without having to use command line or a separate Git GUI. That would be a lower barrier for many users,

One more thing (which is something I haven't yet thought :) ) is conflict resolution. But maybe the workflow first.

**Comment by oliver----** [comment]
@michael be careful with your proposal and the assumption that git is the solution collaboration in our case. If it was we would not need the whole OT stuff at all.
Git works *pretty* well for unstructured text files (such as source code, or markdown files). It does not work for XML files, at least not without a XML aware diff/merge tool.

It will not be very likely that we will provide a conflict resolution UI, because this exposes the complexity of git conflicts to users which I don't think is easy to grasp. Also it requires an XML aware diff/merge tool.
The idea with combining git and OT was primarily, to have an easy to implementation file-system based, that can deal with binaries and allows rolling back etc.
If we used unstructured text files as serialization format, we could allow for a collaboration between coders and clickers, where clickers contributed PR (using OT based group authoring) and coders work with git directly, doing merges and resolving conflicts.

**Comment by michael** [comment]
As @oliver---- mentioned with this workflow you are likely to experience merge issues, as Git does not work well with XML content. There are tools to help with [merging XML](https://joepairman.com/posts/xml-in-git-mercurial-watch-out-for-merges). In the long run we will additionally provide realtime collaboration, and automated merging of XML diffs (the editor will do the XML merge for you, and just highlight places you should review after the merge)
