### ISSUE TITLE
Update cell ranges during inserting/deleting row/col

### ISSUE THREAD

**Issue by michael** [stencila/stencila#595]
This must happen in one transaction. We may need an index over all cells which have ranges (A1:A2) and references (A1:A1).

**Comment by Integral** [comment]
After some thinking and playing with this issue I clearly see that me need to discuss it.
This isn't something very easy and will certainly require some new API, probably a new manager.
So what do we actually need? As you said we need a few indexes: by column and by row, so we can ask this API: give me all cells which are referring for instance to deleted row/column. And then expand/shift given range or reference.
We can't use a NodeIndex for that, because it wan't be able to detect engine input changes (only cell value changes). We will rather need some sort of manager, like issue manager which will keep these indexes and will listen for all cell state changes (to detect range changes for example) and update them. Otherwise we will need to implement again what is already done by engine (transformation between A1:A3 to coordinates within table).
All in all it feels a bit like part of a bigger sheet API changes. I wonder what @oliver---- thinks about implementing it now.
