### ISSUE TITLE
Saving cell data when moving away with arrow key

### ISSUE THREAD

**Issue by jure** [stencila/stencila#601]
This is a feature request/discussion of sorts: when you're editing a cell in Excel or Google Sheets, when you press an arrow key the edit is saved and the cell selection is moved in the direction of the arrow key.

In Stencila Sheets, if you do the above, you're just navigating/moving the cursor in the cell's text field. This isn't necessarily worse, but it is different from what people are used to when it comes to spreadsheets.

**Comment by nokome** [comment]
Thanks for the suggestion @jure. I just tried it in Google Sheets and Libre Office and the behaviour is as in Stencila - arrow keys move the cursor inside the cell's text. Seems to me that it would be important to retain this behaviour so that you can go back and edit cell text from the keyboard without having to use the mouse to place the cursor in the text. Maybe Excel only moves to the adjacent cell on arrow keypress if the cursor is at the end of the text and you press up , down or right arrow (but not left)?

**Comment by jure** [comment]
Hm, interesting. I wonder why my Google Sheets behaves differently. Recorded a quick video of it:

![feb-27-2018 08-22-26](https://user-images.githubusercontent.com/238667/36717840-902aca6a-1b97-11e8-8003-371af996efe6.gif)

**Comment by michael** [comment]
@jure what if you press the left arrow key, it would put the cursor into the previous character right? At least until hit the first one (where tge could also jump out of the cell)

Also: How did you record that gif? :) Nice to see the key presses.

**Comment by jure** [comment]
Yeah, it’s a fun gif :) Keycastr I think the app is called. 

Actually, pressing left arrow
also jumps out. If however, you specifically place the cursor in the middle of the cell using your mouse, then left and right arrows work as normal.

Maybe it’s a setting in my computer, but both Google Sheets and Excel work like that for me. Do they also work differently for you?

**Comment by oliver----** [comment]
I can confirm that there are two different behaviors in Excel, GSheet, and Pages (all under OSX) depending on how the cell is edited.
When typing-over, I see the same behavior as @jure. If I double-click into it, or type-over and click into it, it works as in Stencila.
