### ISSUE TITLE
A minimalist article view

### ISSUE THREAD

**Issue by michael** [stencila/stencila#607]
Thought about removing the clutter from the interface (abstract, authors, references, footnotes if empty). Adding them would work via ellipsis menu.

Current empty article looks like this:

![image](https://user-images.githubusercontent.com/2931/36790596-ab5b434c-1c95-11e8-9838-3961a4c04546.png)

New interface:

![image](https://user-images.githubusercontent.com/2931/36789524-28d0a06e-1c92-11e8-8d0a-b1d4de542c86.png)

**Comment by michael** [comment]
Once an article is fully built out it could look like so:

![image](https://user-images.githubusercontent.com/2931/36789562-4f1affda-1c92-11e8-838f-29e5c83719ec.png)

- suggesting to show the TOC on demand (if there are more than 2 sections) and if there is enough screen space (we can apply a bit of responsive design here). that way we can keep the context bar in the Project scope (not part of the editor but injected). If you bring up the help panel for instance the TOC would likely disappear just because there's not enough space.

**Comment by michael** [comment]
Some UX flow ideas:

- Add first reference: click on item in ellipsis menu brings up modal dialog for entering the data
- Add Abstract: it would show a placeholder and move the cursor there, if you don't fill it out the placeholder will stay there until you reload (then you need to click add abstract again).

**Comment by michael** [comment]
Here's another mock if there is not enough screen space to show the TOC:

![image](https://user-images.githubusercontent.com/2931/36790519-5ec18140-1c95-11e8-990e-04b1703e669c.png)

**Comment by gmaciocci** [comment]
I like the general direction you're heading towards - streamlined without becoming obscure. I am not 100% sure about the ellipsis icon being the best fit for manuscript - critical  functions however, it always feels a bit like a catch-all cop-out UI element and has a tendency to become overloaded as software evolves. That's where I'd expect options like Preferences and New Document/New Sheet to be. 

If you're only dealing with first-time insertion, a '+'  menu might work, with a subtle "edit" call to action being added directly to the relevant section once in the document.

**Comment by nokome** [comment]
Hey @michael these mocks look great. I like your ideas for TOC display.

Instead of the ellipsis menu item how about a "Metadata" or "Sections" menu before the "Cite" menu with toggling menu items for "Abstract", "Authors", "References" etc. (or "Add Abstract" etc if its going to be an issue to toggle off a section once it is created). Then use the current UX flow once those sections are created i.e a  small '+' button to add a new author, reference, or footnote once those sections are created.

One more request: could we put the Article vertical scrollbar on the right.

**Comment by michael** [comment]
@gmaciocci @nokome true there may be better places than the ellipsis menu (if we need it yet at all). I mean I expect as functionality grows we need some kind of primary menu, where we put all the not so frequently used stuff. I'd need to implemented nested menu's first then so we can do: `Menu > Insert > Blockquote` etc.

How about putting the toggles into the View menu?

So we have: 

```
View
   - Show/Hide Title
   - Show/Hide Abstract
   - Show/Hide Authors
   - Show/Hide References
   - -------
   - Show All Code
   - Hide All Code
```

Putting the scrollbar to the right is fine with me. The reason having it left was because of the Lens-ish design where we needed the context (sidepanel) be close to the content. It would look ugly if there's a scrollbar in between. I'd even switch to using a native scrollbar for now until we put highlighting back into place.

**Comment by michael** [comment]
I'm not really convinced, but while playing around with the CSS a bit, I came to to this grey background with a white paper on it design. Posting it here just to have it recorded.

![image](https://user-images.githubusercontent.com/2931/36862535-5f0f2146-1d87-11e8-8ea7-4cde6e17649f.png)

**Comment by gmaciocci** [comment]
If you don’t mind me saying so it’s a little old fashioned. I’d recommend sticking with the white background and using white space and alignment to delineate functional areas.

**Comment by michael** [comment]
Yeah you are indeed right. That's so 2011. Like how substance.io looked back then. 

Guess I was just getting nostalgic...  Watch: https://vimeo.com/27730207 

Here's what I got so far:

![image](https://user-images.githubusercontent.com/2931/36870062-1d54c802-1d9e-11e8-8b21-acaf741b3883.png)

**Comment by NickDuffield** [comment]
@michael I like the idea of the decluttered interface. I think that less clutter helps people focus on their task at hand, and generally makes the interface easier to understand. There is a balance to be struck though, and you will need to user test this. Taking the direction too far can mean that your controls are hard to find. A way to solve this is to make sure that your tools are focused, logically grouped, clearly labelled and placed where people would expect to find them.

I agree with Giuliano that the dot icon is sometimes used as a dumping ground for other or misc type links and is typically used to save space. Take a look at the google docs use in their tool bar. If you drag the browser to become smaller you will see more dots. Eventually the dots almost become meaningless. 

I like the hide/show toc idea, especially if you are trying to make the design more responsive and handle varying screen sizes. I do think that menu icon looks like an text alignment though. I think we night need to figure out the best placement of all of the tool panels and navigation controls generally, especially if you are considering adding a qc pane.

Any chance you can send me a complete list of control panes so that I can mull over it for you?

**Comment by gmaciocci** [comment]
@michael the third screenshot on this page is the cleanest and most appealing one in my opinion. The left pane's content is top-aligned to the main pane's, the ToC links are lighter than the content (as they should be) which let you highlight the currently selected one without overdoing it, and there's a nice separation between section links (maybe even a touch too much).  I'd stick with that for now and focus on the more functional aspects :).

**Comment by gmaciocci** [comment]
Love it! Quick note: dropdown menus like the View menu should really hide when you click outside of them ;)

**Comment by michael** [comment]
Oh yes! We are well aware of that. We want to solve this properly by introducing an app-state concept (see https://github.com/substance/substance/issues/1130)

We really need to find some time to do a bigger iteration on Substance core features. Will do after the Stencila release!
