### ISSUE TITLE
Code trying to run in Javascript when is R or python

### ISSUE THREAD

**Issue by finlay** [stencila/stencila#61]
Fresh install on my computer.

**Comment by nokome** [comment]
Its hard to see how this happened but somehow `this.contexts` must have been undefined on this line:

https://github.com/stencila/stencila/blob/e43e7468dcde62ffa482cb0f9c8d0d21c2c32727/js/stencila.js#L1289

so it tried to render the stencil in JS rather than do a Websocket call to the R session. 1ffa64b should hopefully fix it. Something that is a bit hard to think of a unit test for.
