### ISSUE TITLE
Allow user to force re-execute a cell

### ISSUE THREAD

**Issue by apawlik** [stencila/stencila#637]
In order to rerun a cell after another one on which it depends on changes, you need to actually modify the cell contents (Shift+Enter doesn't work). GIF to demonstrate that to follow soon.

**Comment by nokome** [comment]
I think the title of this should be changed to "Allow user to force re-execute a cell". The screencast below illustrates that dependant cells can be rerun without modification (`y` turns to yellow when `x` changes). It didn't work for the example we were discussing this morning (a cell in which there was a function definition) because currently the JS syntax parser does not recognise a function as an output (although we could add that). 

But what isn't working is the user being able to force rexecution of a cell even if dependants or the cell itself hasn't changed - like this example using random number generation - you need to change the cell content for it to re-execute.

![peek 2018-04-16 14-32](https://user-images.githubusercontent.com/1152336/38787731-f236ec0e-4183-11e8-88b8-0501056e020e.gif)

**Comment by apawlik** [comment]
That is  all true. Thank you!

**Comment by oliver----** [comment]
Thanks for the nice report. Will work on this now.

**Comment by oliver----** [comment]
This is how it looks like when merging PR #650:
![stencila-force-update](https://user-images.githubusercontent.com/284099/39405872-be0f96e8-4bd7-11e8-93c2-0e474a2c7416.gif)

I.e. only the cell that the user asked for is forced to re-execute.
@nokome @apawlik is this it?

**Comment by oliver----** [comment]
BTW, at the moment keyboard short-cut is `Shift+Enter`

**Comment by nokome** [comment]
Thanks @oliver---- , perfect!
