### ISSUE TITLE
Strong/emphasis buttons missing in Stencila

### ISSUE THREAD

**Issue by michael** [stencila/stencila#653]
Maybe a config issue, need to investigate.

**Comment by oliver----** [comment]
This because https://github.com/substance/texture/commit/e9431a603bdfcb31d37db12a752f1c892e44ad99
introduced a new command-group, 'formatting-primary'.
I think it is not a good idea to go down this route. As we see, changing such a basic is having a massive impact.
The change was done to allow a context-menu have only bold and italic.
Instead we need to think about how to approach this generally, facing an n-to-m configuration problem, which will lead to a segmentation of commands into arbitrary looking groups.
So, we need a better solution to this.

@Integral could you roll-back the mentioned changes?

**Comment by oliver----** [comment]
... and when this done, check if it is working here again

**Comment by Integral** [comment]
Sorry to hear that. I think that happened while I was working on texture table editor (row/column commands). Michael prepared an example for me, I was supposed to remove it afterwards, but it never happened. Sorry.
Agree that the problem is wider than this small accident, it's hard to keep in mind every project (and we have not much yet), maybe we should keep configs inside projects for a better safety?
Anyways, the fix is here: substance/texture#504

**Comment by oliver----** [comment]
Thanks!

**Comment by oliver----** [comment]
Yeah, we need to a bit more careful with such concept changes. Even more if it seems to be just experimental.

**Comment by oliver----** [comment]
@michael do have some more texture changes pending? Would be good to upgrade Texture in Stencila.

**Comment by michael** [comment]
I do, but need some more time to finish. Feel free to create a preview version meanwhile.

**Comment by oliver----** [comment]
No worries. Take your time.

**Comment by michael** [comment]
Published a new Texture version and used it from Stencila. So this is now fixed.
