### ISSUE TITLE
starwars example error

### ISSUE THREAD

**Issue by de-code** [stencila/stencila#703]
Trying to open the Starwars example is showing the following error:

`ERROR:Invalid dimension: row 2 has 11 cells, expected 10.`

(using Stencila Desktop)

**Comment by nokome** [comment]
Thanks, I'm not sure why this didn't come up before. The Sheet importer must be more strict now. The source of this problem was actually the original CSV file (which had commas in some field values :scream: ). I've removed the example. We're moving towards having a set of more completed (and maintained) examples in https://github.com/stencila/examples

**Comment by de-code** [comment]
Thank you. Shame I will never find out what Starwars looks like in Stencila.
